### ISSUE TITLE
Total disease number of VinDr-CXR

### ISSUE THREAD

**Issue by Kingofolk** [xq141839/DualAttNet#1]
Hi, thanks for your great work! I am writing to figure out the total number of diseases your model can detect in the VinDr-CXR dataset? Is it only 14 classes? Could it detect all 22 local diseases? I ask this because I found the official paper of VinDr-CXR said their dataset has annotations for 22 local abnormalities instead of only 14 classes used in the Kaggle competition.
Thanks a lot!
best
Kingofolk

**Comment by xq141839** [comment]
Hello, thanks for your attention to our work. we used the dataset (14 classes) in the Kaggle competition for our experiment.
